export const allWeatherCodes = {
    0: "Unknown",
    1000: ["Clear", "clear_day.svg", "clear_night"],
    1100: ["Mostly Clear", "mostly_clear_day.svg", "mostly_clear_night.svg"],
    1101: ["Partly Cloudy", "partly_cloudy_day.svg", "partly_cloudy_night.svg"],
    1102: ["Mostly Cloudy", "mostly_cloudy.svg"],
    1001: ["Cloudy", "cloudy.svg"],
    2000: ["Fog", "fog.svg"],
    2100: ["Light Fog", "fog_light.svg"],
    4000: ["Drizzle", "drizzle.svg"],
    4001: ["Rain", "rain.svg"],
    4200: ["Light Rain", "rain_light.svg"],
    4201: ["Heavy Rain", "rain_heavy.svg"],
    5000: ["Snow", "snow.svg"],
    5001: ["Flurries", "flurries.svg"],
    5100: ["Light Snow", "snow_light.svg"],
    5101: ["Heavy Snow", "snow_heavy.svg"],
    6000: ["Freezing Drizzle", "freezing_drizzle.svg"],
    6001: ["Freezing Rain", "freezing_rain.svg"],
    6200: ["Light Freezing Rain", "freezing_rain_light.svg"],
    6201: ["Heavy Freezing Rain", "freezing_rain_heavy.svg"],
    7000: ["Ice Pellets", "ice_pellets.svg"],
    7101: ["Heavy Ice Pellets", "ice_pellets_heavy.svg"],
    7102: ["Light Ice Pellets", "ice_pellets_light.svg"],
    8000: ["Thunderstorm", "tstorm.svg"],
  };